version: "3.9"

services:
  db:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    container_name: cv_db
    environment:
      - POSTGRES_DB=cv_db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv-backend-go
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://devuser:admin@db:5432/cv_db?sslmode=disable
    depends_on:
      - db
    entrypoint: [ "/app/wait-for.sh", "db:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]


volumes:
  dev-db-data: