// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"
)

type CvEducation struct {
	ID          int32     `json:"id"`
	Institution string    `json:"institution"`
	Degree      string    `json:"degree"`
	StartDate   time.Time `json:"start_date"`
	EndDate     time.Time `json:"end_date"`
	CvProfileID int32     `json:"cv_profile_id"`
}

type CvProfile struct {
	ID             int32          `json:"id"`
	Name           string         `json:"name"`
	Email          string         `json:"email"`
	Phone          string         `json:"phone"`
	Address        string         `json:"address"`
	LinkedinUrl    sql.NullString `json:"linkedin_url"`
	GithubUrl      string         `json:"github_url"`
	Bio            string         `json:"bio"`
	CreatedAt      time.Time      `json:"created_at"`
	ProfilePicture string         `json:"profile_picture"`
}

type Project struct {
	ID               int32  `json:"id"`
	Title            string `json:"title"`
	ShortDescription string `json:"short_description"`
	Description      string `json:"description"`
	Image            string `json:"image"`
	HexThemeColor    string `json:"hex_theme_color"`
	ProjectUrl       string `json:"project_url"`
	CvProfileID      int32  `json:"cv_profile_id"`
	Significance     int32  `json:"significance"`
}

type ProjectTechnology struct {
	ProjectID    int32 `json:"project_id"`
	TechnologyID int32 `json:"technology_id"`
}

type Skill struct {
	ID            int32  `json:"id"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Category      string `json:"category"`
	Image         string `json:"image"`
	HexThemeColor string `json:"hex_theme_color"`
	CvProfileID   int32  `json:"cv_profile_id"`
	Importance    int32  `json:"importance"`
}

type Technology struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	Url        string `json:"url"`
	OrderField int32  `json:"order_field"`
}
