// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: project.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (title,
                      short_description,
                      description,
                      image,
                      technologies_used,
                      hex_theme_color,
                      project_url,
                      cv_profile_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, title, short_description, description, image, technologies_used, hex_theme_color, project_url, cv_profile_id
`

type CreateProjectParams struct {
	Title            string   `json:"title"`
	ShortDescription string   `json:"short_description"`
	Description      string   `json:"description"`
	Image            string   `json:"image"`
	TechnologiesUsed []string `json:"technologies_used"`
	HexThemeColor    string   `json:"hex_theme_color"`
	ProjectUrl       string   `json:"project_url"`
	CvProfileID      int32    `json:"cv_profile_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.Title,
		arg.ShortDescription,
		arg.Description,
		arg.Image,
		pq.Array(arg.TechnologiesUsed),
		arg.HexThemeColor,
		arg.ProjectUrl,
		arg.CvProfileID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ShortDescription,
		&i.Description,
		&i.Image,
		pq.Array(&i.TechnologiesUsed),
		&i.HexThemeColor,
		&i.ProjectUrl,
		&i.CvProfileID,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id,
       title,
       description,
       image,
       technologies_used,
       hex_theme_color,
       project_url,
       cv_profile_id
FROM projects
WHERE id = $1
`

type GetProjectRow struct {
	ID               int32    `json:"id"`
	Title            string   `json:"title"`
	Description      string   `json:"description"`
	Image            string   `json:"image"`
	TechnologiesUsed []string `json:"technologies_used"`
	HexThemeColor    string   `json:"hex_theme_color"`
	ProjectUrl       string   `json:"project_url"`
	CvProfileID      int32    `json:"cv_profile_id"`
}

func (q *Queries) GetProject(ctx context.Context, id int32) (GetProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Image,
		pq.Array(&i.TechnologiesUsed),
		&i.HexThemeColor,
		&i.ProjectUrl,
		&i.CvProfileID,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id,
       title,
       short_description,
       image,
       technologies_used,
       hex_theme_color,
       project_url,
       cv_profile_id
FROM projects
WHERE cv_profile_id = $1
ORDER BY technologies_used
LIMIT $2 OFFSET $3
`

type ListProjectsParams struct {
	CvProfileID int32 `json:"cv_profile_id"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

type ListProjectsRow struct {
	ID               int32    `json:"id"`
	Title            string   `json:"title"`
	ShortDescription string   `json:"short_description"`
	Image            string   `json:"image"`
	TechnologiesUsed []string `json:"technologies_used"`
	HexThemeColor    string   `json:"hex_theme_color"`
	ProjectUrl       string   `json:"project_url"`
	CvProfileID      int32    `json:"cv_profile_id"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, arg.CvProfileID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ShortDescription,
			&i.Image,
			pq.Array(&i.TechnologiesUsed),
			&i.HexThemeColor,
			&i.ProjectUrl,
			&i.CvProfileID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
