// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: project_skill.sql

package db

import (
	"context"
)

const createProjectSkill = `-- name: CreateProjectSkill :one
INSERT INTO project_skills
(project_id,
 skill_id)
VALUES ($1, $2)
RETURNING project_id, skill_id
`

type CreateProjectSkillParams struct {
	ProjectID int32 `json:"project_id"`
	SkillID   int32 `json:"skill_id"`
}

func (q *Queries) CreateProjectSkill(ctx context.Context, arg CreateProjectSkillParams) (ProjectSkill, error) {
	row := q.db.QueryRowContext(ctx, createProjectSkill, arg.ProjectID, arg.SkillID)
	var i ProjectSkill
	err := row.Scan(&i.ProjectID, &i.SkillID)
	return i, err
}
