// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	CreateCvEducation(ctx context.Context, arg CreateCvEducationParams) (CvEducation, error)
	CreateCvProfile(ctx context.Context, arg CreateCvProfileParams) (CvProfile, error)
	CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error)
	GetCvEducation(ctx context.Context, id int32) (CvEducation, error)
	GetCvProfile(ctx context.Context, id int32) (CvProfile, error)
	GetSkill(ctx context.Context, id int32) (Skill, error)
	ListCvEducations(ctx context.Context, arg ListCvEducationsParams) ([]CvEducation, error)
	ListSkills(ctx context.Context, arg ListSkillsParams) ([]Skill, error)
}

var _ Querier = (*Queries)(nil)
