// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	CreateCvEducation(ctx context.Context, arg CreateCvEducationParams) (CvEducation, error)
	CreateCvProfile(ctx context.Context, arg CreateCvProfileParams) (CvProfile, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error)
	GetCvEducation(ctx context.Context, id int32) (CvEducation, error)
	GetCvProfile(ctx context.Context, id int32) (CvProfile, error)
	GetProject(ctx context.Context, id int32) (Project, error)
	GetSkill(ctx context.Context, id int32) (Skill, error)
	ListCvEducations(ctx context.Context, arg ListCvEducationsParams) ([]CvEducation, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListSkills(ctx context.Context, arg ListSkillsParams) ([]Skill, error)
}

var _ Querier = (*Queries)(nil)
