// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	CreateCvProfile(ctx context.Context, arg CreateCvProfileParams) (CvProfile, error)
	GetCvProfile(ctx context.Context, id int32) (CvProfile, error)
}

var _ Querier = (*Queries)(nil)
